services:
  - type: web
    name: fastapi-scraper
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y chromium-browser chromium-chromedriver
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
